[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "foo"

[[bin]]
name = "baz"
path = "src/baz.rs"

[dependencies]
