---
name: Test install-github-release-binary
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install semantic-release-action/test-rust-multiple-binary-workspace/foo
        uses: EricCrosson/install-github-release-binary@beta
        with:
          targets: |
            semantic-release-action/test-rust-multiple-binary-workspace/foo@v1
            semantic-release-action/test-rust-multiple-binary-workspace/bar@v1

      - run: which foo
      - run: foo

      - run: which bar
      - run: bar
